name: first action
"on":
    push:
        branches:
            - "release/*"

    pull_request:
      types:
        - opened
        - reopened

    workflow_dispatch:

jobs:
    hello-ubuntu:
        runs-on: ubuntu-22.04
        steps:
            - run: echo "this is the first step out of a 3 steps job. it has no prerequisites"
            - run: echo "hello world by ubuntu!"
            - run: echo "It might has dependent downstream jobs"

    hello-python:
        runs-on: ubuntu-22.04
        steps:
            - run: print("hello from python")
              shell: python
        needs:
            - hello-ubuntu

    hello-thirdparty:
        runs-on: ubuntu-latest
        steps:
            - uses: jairogomz/hello-world-javascript-action-by-jairo@v1.0.1
              with:
                who-to-greet: Omar
        needs: 
            - hello-ubuntu
            - hello-python

    visualize-metadata:
        runs-on: ubuntu-22.04
        steps:
            - name: "print gitflow metadata"
              run: |
                echo "printing $GITHUB_EVENT_NAME content"
                echo "rendering the github event path"
                cat "$GITHUB_EVENT_PATH"





