name: first action
"on":
    push:
        branches:
            - "release/*"
    pull_request:
        types:
            - opened
            - reopened
        paths: 
            - "backend/*"
            - "!frontend/*"
    workflow_dispatch:

env:
    WORKFLOW_GLOBAL: "IAM A TEST FLOW"

jobs:
    hello-ubuntu:
        env:
            JOB_VAR: "IAM UBUNTU 22"
        runs-on: ubuntu-22.04
        steps:
            - run: echo "this is the first step out of a 3 steps job. it has no prerequisites"
            - run: echo "hello world by ubuntu!...Iam running >> $JOB_VAR -- Within the flow >> $WORKFLOW_GLOBAL"
            - run: echo "It might has dependent downstream jobs"

    hello-python:
        runs-on: ubuntu-22.04
        steps:
            - name: python-job
              env:
                STEP_VAR: "step var for python"
              run: |
                import os
                print("hello from python")
                print(f"reading step var: {os.getenv('STEP_VAR')}")
              shell: python
        needs:
            - hello-ubuntu

    hello-thirdparty:
        runs-on: ubuntu-latest
        steps:
            - uses: jairogomz/hello-world-javascript-action-by-jairo@v1.0.1
              with:
                who-to-greet: Omar
        needs: 
            - hello-ubuntu
            - hello-python

    visualize-metadata:
        runs-on: ubuntu-22.04
        steps:
            - name: "print gitflow metadata"
              run: |
                echo "printing $GITHUB_EVENT_NAME content"
                echo "rendering the github event path"
                cat "$GITHUB_EVENT_PATH"