name: deploy-backend
on:
    workflow_dispatch:

    # push:
    #     branches: 
    #     - "release/*"
    #     paths:
    #         - "backend/**"
    #         - '.github/workflows/backend.yaml'
    #         - 'infra/*'
env:
    artifact_dir: .artifacts
jobs:
  deploy-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    env:
      TF_VAR_HF_TOKEN             : ${{secrets.TF_VAR_HF_TOKEN}}
      TF_VAR_MYSQL_PASSWORD       : ${{secrets.TF_VAR_MYSQL_PASSWORD }}
      TF_VAR_MYSQL_ROOT_PASSWORD  : ${{secrets.TF_VAR_MYSQL_ROOT_PASSWORD}}
    steps:
        - name: checkout-repo
          uses: actions/checkout@v5

        - name: init
          uses: ./.github/actions/init
          with:
            tf_hf_token     : ${{env.TF_VAR_HF_TOKEN}}
            tf_db_pass      : ${{env.TF_VAR_MYSQL_PASSWORD }}
            tf_db_root_pass : ${{env.TF_VAR_MYSQL_ROOT_PASSWORD}}
            aws_region      : "eu-central-1"
            aws_key_id      : ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret      : ${{secrets.AWS_SECRET_ACCESS_KEY}}

        - name: deploy-db
          id: db
          continue-on-error: false
          run: terraform apply -target=module.aurora --auto-approve
