name: deploy-backend
"on":
    workflow_dispatch:

    push:
        branches: 
        - "release/*"
        # paths:
        #     - "backend/**"
        #     - '.github/workflows/backend.yaml'
        #     - 'infra/*'
env:
    artifact_dir: .artifacts

jobs:
    deploy-vpc-ssm:
        runs-on: ubuntu-22.04
        defaults:
          run:
            working-directory: ./infra
        env:
          TF_VAR_HF_TOKEN             : ${{secrets.TF_VAR_HF_TOKEN}}
          TF_VAR_MYSQL_PASSWORD       : ${{secrets.TF_VAR_MYSQL_PASSWORD }}
          TF_VAR_MYSQL_ROOT_PASSWORD  : ${{secrets.TF_VAR_MYSQL_ROOT_PASSWORD}}
        steps:
            - name: checkout-repo
              uses: actions/checkout@v5

            - name: auth-aws
              uses: aws-actions/configure-aws-credentials@main
              with:
                aws-region: "eu-central-1"
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

            - name: setup-terraform
              uses: hashicorp/setup-terraform@v3

            - name: init-terraform
              run: |
               echo "current working dir: ${PWD}"
               terraform init
               terraform validate
              
            - name: plan-vpc
              id: plan-vpc
              continue-on-error: false
              run: |
                terraform plan -target=module.vpc
                echo "terraform step exit code: ${{steps.plan-vpc.outputs.exitcode}}"

            - name: apply-vpc
              id: vpc
              continue-on-error: false
              run: |
                terraform apply -target=module.vpc --auto-approve
                # terraform output -json outputs.json

            - name: deploy-ssm
              id: ssm
              continue-on-error: false
              run: |
                echo ""
                terraform apply -target=module.ssm --auto-approve


            - name: read-state
              id: read-state
              run: 
                set +x
                echo "--------------------------------------"
                echo "returning assets in the current state:"
                terraform state list