name: "deploy-cloudfront"
"on":
    push:
        branches: 
        - "release/*cloudfront*"
        paths:
          - ./frontend/*
          - ./.github/workflows/cloudfront.yml
        

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5

            - name: build frontend static files
              run: |
                cd ./frontend
                npm install
                npm run build

            - name: archive static files
              uses: actions/upload-artifact@v4
              with:
                name: static_files
                path: ./frontend/dist

    upload-to-origin:
        runs-on: ubuntu-latest
        steps:
            - name: retrieve artifact
              uses: actions/download-artifact@v4
              with:
                name: static_files
                path: ./release/
            - name: validate artifact
              run: |
                nlines=$(wc -l < ./release/dist/index.html)
                if ["$nlines" -gt 1 ]; then
                    echo "Successfully built and read static files!!!"
                else
                    echo "Failed to read static files artifact"
                fi

