name: deploy-backend
"on":
    workflow_dispatch:

    # push:
    #     branches: 
    #     - "release/*"
    #     paths:
    #         - "backend/**"
    #         - '.github/workflows/backend.yaml'
    #         - 'infra/*'
env:
    artifact_dir: .artifacts
    TF_VAR_HF_TOKEN             : ${{secrets.TF_VAR_HF_TOKEN}}
    TF_VAR_MYSQL_PASSWORD       : ${{secrets.TF_VAR_MYSQL_PASSWORD }}
    TF_VAR_MYSQL_ROOT_PASSWORD  : ${{secrets.TF_VAR_MYSQL_ROOT_PASSWORD}}

jobs:
    deploy-vpc-ssm:
        runs-on: ubuntu-22.04
        outputs:
          ecs_dns: ${{ steps.alb.outputs.dns}}
        defaults:
          run:
            working-directory: ./infra
        steps:
            - name: checkout-repo
              uses: actions/checkout@v5
            
            - name: init-workflow
              uses: ./.github/actions/init
              with:
                tf_hf_token         : ${{env.TF_VAR_HF_TOKEN}}
                tf_db_password      : ${{env.TF_VAR_HF_TOKEN}}
                tf_db_root_password : ${{env.TF_VAR_HF_TOKEN}}
                aws_key_id          : ${{secrets.AWS_ACCESS_KEY_ID}}
                aws_secret          : ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws_region          : "eu-central-1"

            - name: apply-alb
              id: alb
              continue-on-error: false
              run: |
                set +x
                echo "-------------------------------------------"
                echo "Deploying ALB Module......................."
                terraform apply -target=module.alb --auto-approve
                echo "-------------------------------------------"
                echo "Writing ALB DNS to app_dns git output"
                echo "dns=terraform output app_dns" >> "$GITHUB_OUTPUT"
                echo "-------------------------------------------"
              
            - name: apply-ecs
              id: ecs
              continue-on-error: false
              run: |
                set +x
                echo "-------------------------------------------"
                echo "Deploying Fargate Module......................."
                terraform apply -target=module.fargate --auto-approve
                echo "-------------------------------------------"

            - name: DNS
              id: dns
              run: |
                set +x
                terraform refresh &> /dev/null
                echo "App url at:"
                terraform output app_dns
                echo "-------------------------------------------"
