name: Create Distributable
on:
    workflow_dispatch:
    push:
        branches:
            - release/*

jobs:
    compile_script:
        outputs:
            installer: ${{steps.compile-script.outputs.compile-script}}
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo content
              uses: actions/checkout@v5

            - name: compile-script
              id: compile-script
              run: |
                chmod 777 ./release
                docker run --rm -i -v $PWD:/work amake/innosetup ./release/setup.iss

            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: SpeechCollector-Installer
                path: ./release/Output


    

    
            
